sonar.projectKey=Frontend-Angular
sonar.projectName=Frontend Angular
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=src

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info

sonar.host.url=http://localhost:9000
sonar.login=sqp_5df210e7079f64ee05713af634aca9dbc56b62a7